fix logs and update error handling!

diff --git a/deby b/deby
--- a/deby
+++ b/deby
@@ -35,7 +35,6 @@ function logo() {
 
     local blue=$(tput setaf 4; tput bold)
     local indigo=$(tput setaf 5; tput bold)
-    local text_color=$(tput bold)
 
     local screen_width=$(tput cols)
     local logo="
@@ -59,7 +58,6 @@ function logo() {
     printf "\n%*s%s%s%*s\n\n" $((($screen_width - ${#text} - 1) / 2)) "" "$blue" "$text" $((($screen_width + ${#text} + ${#text} - $logo_width) / 2)) ""
 
     tput sgr0
-    echo "==== Display Logo" >> "$LOG_FILE"
 }
 
 logo "Press any key to continue..."
@@ -85,10 +83,12 @@ fi
 
 # Update package list
 logo "Updating package list..."
+echo "=== Update Package List" >> "$LOG_FILE"
 log_result "apt update" "Update package list" || exit 1
 
 # Install build essentials and git for compiling software
 logo "Installing build essentials and git..."
+echo "=== Install Build Essentials" >> "$LOG_FILE"
 log_result "apt install -y build-essential git curl" "Install build essentials and git" || exit 1
 
 if [[ ! -f "packages" ]]; then
@@ -99,22 +99,22 @@ if [[ ! -f "packages" ]]; then
 fi
 
 logo "Installing packages..."
-echo "==== Installing Packages" >> "$LOG_FILE"
+echo "=== Installing Packages" >> "$LOG_FILE"
 while read package
 do
     if [[ $package == "" ]] || [[ $package == \#* ]]; then
         continue
     fi
     logo "Installing: $package..."
-    log_result "apt install -y \"$package\"" "Install $package"
+    log_result "apt install -y \"$package\"" "Install $package" || exit 1
 done < packages
 
 logo "Switch shell to '${SHELL}'..."
-echo "==== Shell Configuration" >> "$LOG_FILE"
+echo "=== Shell Configuration" >> "$LOG_FILE"
 log_result "chsh -s \"$SHELL\" root && chsh -s \"$SHELL\" \"$USERNAME\"" "Set shells" || exit 1
 
 logo "Setting keymap and console font..."
-echo "==== Keymap and Console Font" >> "$LOG_FILE"
+echo "=== Keymap and Console Font" >> "$LOG_FILE"
 {
     log_result "echo 'XKBMODEL=pc105' > /etc/default/keyboard" "Set keyboard model" &&
     log_result "echo 'XKBLAYOUT=$KEYMAP' >> /etc/default/keyboard" "Set keymap" &&
@@ -125,31 +125,31 @@ echo "==== Keymap and Console Font" >> "$LOG_FILE"
 } || exit 1
 
 logo "Adding no password sudo rights for $USERNAME..."
-echo "==== Sudo Configuration" >> "$LOG_FILE"
+echo "=== Sudo Configuration" >> "$LOG_FILE"
 log_result "echo \"$USERNAME ALL=(ALL:ALL) NOPASSWD: ALL\" > /etc/sudoers.d/nopasswd_sudo && chmod 440 /etc/sudoers.d/nopasswd_sudo" "Set sudo rights" || exit 1
 
 logo "Adding yamete kudasai sound on usb mount / unmount..."
-echo "==== USB Sound Configuration" >> "$LOG_FILE"
+echo "=== USB Sound Configuration" >> "$LOG_FILE"
 log_result "echo -ne \"KERNEL==\\\"sd*\\\", SUBSYSTEM==\\\"block\\\", ENV{DEVTYPE}==\\\"partition\\\", ACTION==\\\"add\\\", ENV{ID_FS_TYPE}!=\\\"vfat\\\", ENV{ID_FS_USAGE}==\\\"filesystem\\\", RUN+=\\\"/usr/bin/aplay /home/$USERNAME/bin/sound/yamete.wav\\\"\\nKERNEL==\\\"sd*\\\", SUBSYSTEM==\\\"block\\\", ENV{DEVTYPE}==\\\"partition\\\", ACTION==\\\"remove\\\", ENV{ID_FS_TYPE}!=\\\"vfat\\\", ENV{ID_FS_USAGE}==\\\"filesystem\\\", RUN+=\\\"/usr/bin/aplay /home/$USERNAME/bin/sound/ahh.wav\\\"\\n\" > /etc/udev/rules.d/99-usb-sound.rules && udevadm control --reload-rules" "Set USB sound rules" || exit 1
 
 logo "Automount USB drive..."
-echo "==== USB Automount" >> "$LOG_FILE"
+echo "=== USB Automount" >> "$LOG_FILE"
 log_result "echo 'UUID=CA18-653E /mnt vfat noauto,nofail,systemd.automount,systemd.idle-timeout=2,systemd.device-timeout=2 0 0' >> /etc/fstab && systemctl daemon-reload && systemctl restart local-fs.target" "Set USB automount" || exit 1
 
 logo "Disabling Screen Tear..."
-echo "==== Screen Tear Configuration" >> "$LOG_FILE"
+echo "=== Screen Tear Configuration" >> "$LOG_FILE"
 log_result "mkdir -p /etc/X11/xorg.conf.d && echo -ne 'Section \"Device\"\n  Identifier \"Intel Graphics\"\n  Driver \"intel\"\n  Option \"TearFree\" \"true\"\nEndSection\n' > /etc/X11/xorg.conf.d/20-intel.conf" "Set screen tear config" || exit 1
 
 logo "Updating Touchpad Configuration..."
-echo "==== Touchpad Configuration" >> "$LOG_FILE"
+echo "=== Touchpad Configuration" >> "$LOG_FILE"
 log_result "echo -ne 'Section \"InputClass\"\n    Identifier \"libinput touchpad catchall\"\n    MatchIsTouchpad \"on\"\n    MatchDevicePath \"/dev/input/event*\"\n    Option \"Tapping\" \"True\"\n    Option \"TappingDrag\" \"True\"\n    Option \"ScrollMethod\" \"Twofinger\"\n    Option \"NaturalScrolling\" \"False\"\n    Option \"DisableWhileTyping\" \"False\"\n    Driver \"libinput\"\nEndSection\n' > /etc/X11/xorg.conf.d/40-libinput.conf" "Set touchpad config" || exit 1
 
 logo "Slock Configuration..."
-echo "==== Slock Configuration" >> "$LOG_FILE"
+echo "=== Slock Configuration" >> "$LOG_FILE"
 log_result "echo -ne '[Unit]\nDescription=Lock X session using slock for user %i\nBefore=sleep.target\n\n[Service]\nUser=%i\nEnvironment=DISPLAY=:0\nExecStartPre=/usr/bin/xset dpms force suspend\nExecStart=/usr/local/bin/slock\n\n[Install]\nWantedBy=sleep.target\n' > /etc/systemd/system/slock@.service" "Set slock service" || exit 1
 
 logo "Github configuration..."
-echo "==== Github Configuration" >> "$LOG_FILE"
+echo "=== Github Configuration" >> "$LOG_FILE"
 if [ "$TOKEN" != "None" ]; then
     log_result "su - \"$USERNAME\" -c \"echo -ne 'https://$USERNAME:$TOKEN@github.com' > ~/.git-credentials && git config --global credential.helper store\"" "Set git config" || exit 1
 else
@@ -157,7 +157,7 @@ else
 fi
 
 logo "Font configuration..."
-echo "==== Font Configuration" >> "$LOG_FILE"
+echo "=== Font Configuration" >> "$LOG_FILE"
 {
     log_result "mkdir -p /usr/share/fonts/truetype" "Create fonts directory" &&
     log_result "cd /usr/share/fonts/truetype && timeout 30s curl -fLo 'FiraCodeNerdFont-Bold.ttf' https://github.com/ryanoasis/nerd-fonts/raw/HEAD/patched-fonts/FiraCode/Bold/complete/Fira%20Code%20Bold%20Nerd%20Font%20Complete.ttf" "Download font" &&
@@ -166,11 +166,11 @@ echo "==== Font Configuration" >> "$LOG_FILE"
 } || echo "Font configuration: Error" >> "$LOG_FILE"
 
 logo "Creating .build folder..."
-echo "==== Build Directory Setup" >> "$LOG_FILE"
+echo "=== Build Directory Setup" >> "$LOG_FILE"
 log_result "su - \"$USERNAME\" -c \"mkdir -p ~/.build\"" "Create build directory" || exit 1
 
 logo "Cloning repositories..."
-echo "==== Cloning Repositories" >> "$LOG_FILE"
+echo "=== Cloning Repositories" >> "$LOG_FILE"
 {
     log_result "su - \"$USERNAME\" -c \"cd ~/.build && git clone https://github.com/nemo256/tily\"" "Clone tily" &&
     log_result "su - \"$USERNAME\" -c \"cd ~/.build && git clone https://github.com/nemo256/st\"" "Clone st" &&
@@ -184,33 +184,44 @@ echo "==== Cloning Repositories" >> "$LOG_FILE"
     log_result "su - \"$USERNAME\" -c \"cd ~/.build && git clone https://github.com/tremc/tremc\"" "Clone tremc"
 } || echo "Cloning repositories: Error" >> "$LOG_FILE"
 
-logo "Installing tily..."
-echo "==== Installing Software" >> "$LOG_FILE"
-log_result "cd /home/$USERNAME/.build/tily && make clean install && cd ../st && make clean install && cd ../dmenu && make clean install && cd ../slock && make clean install && cd ../slstatus && make clean install && cd ../fetchy && make clean install && cd ../ani-cli && chmod +x ani-cli && cp -fvr ani-cli /usr/local/bin/ani-cli && cd ../tty-clock && make && make install && cd ../grabc && make && make install && cd ../tremc && make install" "Install software" || exit 1
+logo "Installing repositories..."
+echo "=== Installing Repositories" >> "$LOG_FILE"
+{
+    log_result "su - \"$USERNAME\" -c \"cd ~/.build/tily && make clean install\"" "Install tily" &&
+    log_result "su - \"$USERNAME\" -c \"cd ~/.build/st && make clean install\"" "Install st" &&
+    log_result "su - \"$USERNAME\" -c \"cd ~/.build/dmenu && make clean install\"" "Install dmenu" &&
+    log_result "su - \"$USERNAME\" -c \"cd ~/.build/slock && make clean install\"" "Install slock" &&
+    log_result "su - \"$USERNAME\" -c \"cd ~/.build/slstatus && make clean install\"" "Install slstatus" &&
+    log_result "su - \"$USERNAME\" -c \"cd ~/.build/fetchy && make clean install\"" "Install fetchy" &&
+    log_result "su - \"$USERNAME\" -c \"cd ~/.build/ani-cli && chmod +x ani-cli && cp -fvr ani-cli /usr/local/bin/ani-cli\"" "Install ani-cli" &&
+    log_result "su - \"$USERNAME\" -c \"cd ~/.build/tty-clock && make && make install\"" "Install tty-clock" &&
+    log_result "su - \"$USERNAME\" -c \"cd ~/.build/grabc && make && make install\"" "Install grabc" &&
+    log_result "su - \"$USERNAME\" -c \"cd ~/.build/tremc && make install\"" "Install tremc"
+} || echo "Installing repositories: Error" >> "$LOG_FILE"
 
 logo "Installing alder..."
-echo "==== Install Alder" >> "$LOG_FILE"
+echo "=== Install Alder" >> "$LOG_FILE"
 log_result "npm install -g @aweary/alder" "Install alder" || exit 1
 
 logo "Installing weather-cli..."
-echo "==== Install Weather CLI" >> "$LOG_FILE"
+echo "=== Install Weather CLI" >> "$LOG_FILE"
 log_result "npm install -g weather-cli" "Install weather-cli" || exit 1
 
 logo "Restoring home directory..."
-echo "==== Home Directory Setup" >> "$LOG_FILE"
+echo "=== Home Directory Setup" >> "$LOG_FILE"
 log_result "su - \"$USERNAME\" -c \"mkdir -p ~/dl ~/vids ~/work\"" "Create home directories" || exit 1
 
 logo "Cloning wals..."
-echo "==== Clone Wals" >> "$LOG_FILE"
+echo "=== Clone Wals" >> "$LOG_FILE"
 log_result "su - \"$USERNAME\" -c \"git clone https://github.com/nemo256/wals ~/wals\"" "Clone wals" || exit 1
 
 logo "Removing default configuration files..."
-echo "==== Configuration Cleanup" >> "$LOG_FILE"
+echo "=== Configuration Cleanup" >> "$LOG_FILE"
 log_result "su - \"$USERNAME\" -c \"rm -fvr ~/.bash* ~/.gitconfig ~/.config/*\"" "Remove default configs" || exit 1
 
 # Get list of programs
 programs=$(find "/root/dots/config" -maxdepth 1 -mindepth 1 -type d -printf "%f\n")
-echo "==== Stowing Configurations" >> "$LOG_FILE"
+echo "=== Stowing Configurations" >> "$LOG_FILE"
 if [ -n "$programs" ]; then
     logo "Stowing configuration files..."
     for program in ${programs}; do
@@ -231,7 +242,7 @@ fi
 # log_result "su - \"$USERNAME\" -c \"sed -i 's/nick = \".*\"/nick = \"$IRSSI_USERNAME\"/' ~/.irssi/config\"" "Set irssi nick" || exit 1
 
 logo "Make binary files executable..."
-echo "==== Binary Permissions" >> "$LOG_FILE"
+echo "=== Binary Permissions" >> "$LOG_FILE"
 log_result "su - \"$USERNAME\" -c \"chmod -R 755 ~/bin\"" "Set bin permissions" || exit 1
 
 # logo "Vimy configuration..."
@@ -242,7 +253,7 @@ log_result "su - \"$USERNAME\" -c \"chmod -R 755 ~/bin\"" "Set bin permissions" 
 # log_result "su - \"$USERNAME\" -c \"mkdir ~/.config/nvim/session\"" "Create nvim session directory" || exit 1
 
 logo "Ranger Configuration..."
-echo "==== Ranger Configuration" >> "$LOG_FILE"
+echo "=== Ranger Configuration" >> "$LOG_FILE"
 log_result "su - \"$USERNAME\" -c \"git clone https://github.com/alexanderjeurissen/ranger_devicons ~/.config/ranger/plugins/ranger_devicons && cd ~/.config/ranger/plugins/ranger_devicons && python -m devicons\"" "Set ranger config" || exit 1
 
 # logo "Protonvpn configuration..."
@@ -255,7 +266,7 @@ log_result "su - \"$USERNAME\" -c \"git clone https://github.com/alexanderjeuris
 # log_result "su - \"$USERNAME\" -c \"protonvpn-cli config --vpn-accelerator enable\"" "Enable VPN accelerator" || exit 1
 
 logo "Ly configuration..."
-echo "==== Ly Configuration" >> "$LOG_FILE"
+echo "=== Ly Configuration" >> "$LOG_FILE"
 {
     log_result "apt install -y libpam0g-dev libxcb-xkb-dev" "Install Ly dependencies" &&
     log_result "git clone https://github.com/fairyglade/ly /tmp/ly" "Clone Ly" &&
@@ -266,11 +277,11 @@ echo "==== Ly Configuration" >> "$LOG_FILE"
 } || exit 1
 
 logo "Managing Essential Services..."
-echo "==== Service Management" >> "$LOG_FILE"
+echo "=== Service Management" >> "$LOG_FILE"
 log_result "systemctl disable transmission-daemon && systemctl enable bluetooth && systemctl enable slock@$USERNAME && systemctl enable ly" "Manage services" || exit 1
 
 logo "Installing prochot service..."
-echo "==== Prochot Service" >> "$LOG_FILE"
+echo "=== Prochot Service" >> "$LOG_FILE"
 log_result "cp prochot.service /etc/systemd/system/prochot.service && systemctl enable prochot" "Set prochot service" || exit 1
 
 logo "Done - Script finished installing and configuring n3m0's dots!"
