fix logs and update error handling!

diff --git a/deby b/deby
--- a/deby
+++ b/deby
@@ -119,7 +119,7 @@ echo "==== Keymap and Console Font" >> "$LOG_FILE"
     log_result "echo 'XKBMODEL=pc105' > /etc/default/keyboard" "Set keyboard model" &&
     log_result "echo 'XKBLAYOUT=$KEYMAP' >> /etc/default/keyboard" "Set keymap" &&
     log_result "echo 'FONT=$CONSOLE_FONT' > /etc/default/console-setup" "Set console font" &&
-    log_result "echo 'CHARMAP=UTF-8' > /etc/default/console-setup" "Set console charset" &&
+    log_result "echo 'CHARMAP=UTF-8' >> /etc/default/console-setup" "Set console charset" &&
     log_result "dpkg-reconfigure -f noninteractive keyboard-configuration" "Apply keyboard configuration" &&
     log_result "dpkg-reconfigure -f noninteractive console-setup" "Apply console setup"
 } || exit 1
@@ -158,7 +158,12 @@ fi
 
 logo "Font configuration..."
 echo "==== Font Configuration" >> "$LOG_FILE"
-log_result "mkdir -p /usr/share/fonts/truetype && cd /usr/share/fonts/truetype && curl -fLo 'FiraCodeNerdFont-Bold.ttf' https://github.com/ryanoasis/nerd-fonts/raw/HEAD/patched-fonts/FiraCode/Bold/complete/Fira%20Code%20Bold%20Nerd%20Font%20Complete.ttf && fc-cache -fv && cd /home/$USERNAME" "Set font config" || exit 1
+{
+    log_result "mkdir -p /usr/share/fonts/truetype" "Create fonts directory" &&
+    log_result "cd /usr/share/fonts/truetype && curl -fLo 'FiraCodeNerdFont-Bold.ttf' https://github.com/ryanoasis/nerd-fonts/raw/HEAD/patched-fonts/FiraCode/Bold/complete/Fira%20Code%20Bold%20Nerd%20Font%20Complete.ttf" "Download font" &&
+    log_result "fc-cache -fv" "Update font cache" &&
+    log_result "cd /home/$USERNAME" "Return to user home"
+} || echo "Font configuration: Error" >> "$LOG_FILE"
 
 logo "Creating .build folder..."
 echo "==== Build Directory Setup" >> "$LOG_FILE"
@@ -169,7 +174,7 @@ echo "==== Cloning Repositories" >> "$LOG_FILE"
 log_result "su - \"$USERNAME\" -c \"git clone https://github.com/nemo256/tily && git clone https://github.com/nemo256/st && git clone https://github.com/nemo256/dmenu && git clone https://github.com/nemo256/slock && git clone https://github.com/nemo256/slstatus && git clone https://github.com/nemo256/fetchy && git clone https://github.com/pystardust/ani-cli && git clone https://github.com/xorg62/tty-clock && git clone https://github.com/muquit/grabc && git clone https://github.com/tremc/tremc\"" "Clone repositories" || exit 1
 
 logo "Installing tily..."
-echo "==== Amendatory
+echo "==== Installing Software" >> "$LOG_FILE"
 log_result "cd tily && make clean install && cd ../st && make clean install && cd ../dmenu && make clean install && cd ../slock && make clean install && cd ../slstatus && make clean install && cd ../fetchy && make clean install && cd ../ani-cli && chmod +x ani-cli && cp -fvr ani-cli /usr/local/bin/ani-cli && cd ../tty-clock && make && make install && cd ../grabc && make && make install && cd ../tremc && make install" "Install software" || exit 1
 
 logo "Installing alder..."
